In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [110]:
name_criterions = []
# [{'name': 'Свердловская область',
#   'year': [{'2014': {'Доля аварийного жилья': 0.6,
#      'Доля детей для определения в ДОУ': 0.4360968153,
#      'Доля населения, обеспеченного безопасной питьевой водой': 0.893831}}]}]

In [77]:
name = 'Свердловская область'
year = 2014
criterions = {}

In [78]:
old_houses = pd.read_excel('Критерии.xlsx', sheet_name=2, skiprows=4).rename(columns={'Unnamed: 0': 'Название'})
old_houses

,Название,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,Unnamed: 16,Данные из ЕМИСС,2014.1,2015
0,Российская Федерация,0.3,0.3,0.4,0.5,0.4,0.4,0.4,0.5,0.5,0.6,0.6,0.6,0.7,0.7,0.7,NaN,Российская Федерация,0.0269,0.0263
1,Центральный федеральный округ,0.1,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.3,0.3,0.3,0.3,0.4,0.3,NaN,Центральный федеральный округ,0.0166,0.0154
2,Белгородская область,0,0.4,0.4,0.4,0.3,0.3,0.3,0.3,0.5,0.5,0.3,0.4,0.4,0.4,0.3,NaN,Северо-Западный федеральный округ,0.0236,0.0250
3,Брянская область,0,0,0.1,0.1,0.1,0.1,0.1,0,0,0,0,0.1,0.1,0.3,0.3,NaN,Южный федеральный округ (с 2010 года),0.0159,0.0159
4,Владимирская область,0,0,0,0,0,0,0,0,0.1,0.2,0.2,0.3,0.4,0.4,0.4,NaN,Северо-Кавказский федеральный округ,0.0654,0.0661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Крымский федеральный округ,…,…,…,…,…,…,…,…,…,…,…,…,…,…,0.1,NaN,NaN,NaN,NaN
95,Республика Крым,…,…,…,…,…,…,…,…,…,…,…,…,…,…,0.1,NaN,NaN,NaN,NaN
96,г. Севастополь,…,…,…,…,…,…,…,…,…,…,…,…,…,…,0.1,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,1)C 2015 г. данные по аварийному жилищному фон...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
old_houses[old_houses['Название'] == name]

,Название,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,Unnamed: 16,Данные из ЕМИСС,2014.1,2015
65,Свердловская область,0,0,0,0,0,0,0,0,0.2,0.3,0.3,0.4,0.4,0.5,0.6,NaN,NaN,NaN,NaN

In [80]:
criterions['Доля аварийного жилья'] = old_houses[old_houses['Название'] == name][year].iloc[0]

In [81]:
children_pre_school = pd.read_excel('Критерии.xlsx', sheet_name=3).rename(columns={'Unnamed: 0': 'Название', 'Unnamed: 7': 'Доля'})
children_pre_school

,Название,"Численность детей, состоящих на учете для определения в дошкольные учреждения, на конец отчетного года, человек",Unnamed: 2,Unnamed: 3,Unnamed: 4,"Численность детей в возрасте 1 - 6 лет в муниципальном образовании, человек",Unnamed: 6,Доля
0,NaN,Муниципальный район,"Городской округ, городской округ с внутригород...",NaN,NaN,Муниципальный район,"Городской округ, городской округ с внутригород...",NaN
1,NaN,2014,2014,NaN,NaN,2014,2014,NaN
2,значение показателя за год,NaN,NaN,NaN,на 1 января,NaN,NaN,NaN
3,Байкаловский муниципальный район,177,NaN,NaN,Байкаловский муниципальный район,1377,NaN,0.128540
4,Камышловский муниципальный район,528,NaN,NaN,Камышловский муниципальный район,2152,NaN,0.245353
...,...,...,...,...,...,...,...,...
67,городской округ Рефтинский,NaN,307,NaN,городской округ Рефтинский,NaN,1181,0.259949
68,городской округ Пелым,NaN,60,NaN,городской округ Пелым,NaN,312,0.192308
69,городской округ Староуткинск,NaN,105,NaN,городской округ Староуткинск,NaN,258,0.406977
70,Махнёвское муниципальное образование,NaN,128,NaN,Махнёвское муниципальное образование,NaN,532,0.240602
71,Муниципальное образование Алапаевское (с 2010 г.),NaN,455,NaN,Муниципальное образование Алапаевское (с 2010 г.),NaN,2204,0.206443

In [82]:
children_pre_school[children_pre_school['Название'] == 'муниципальное образование "город Екатеринбург"']

,Название,"Численность детей, состоящих на учете для определения в дошкольные учреждения, на конец отчетного года, человек",Unnamed: 2,Unnamed: 3,Unnamed: 4,"Численность детей в возрасте 1 - 6 лет в муниципальном образовании, человек",Unnamed: 6,Доля
8,"муниципальное образование ""город Екатеринбург""",NaN,42792,NaN,"муниципальное образование ""город Екатеринбург""",NaN,98125,0.436097

In [83]:
criterions['Доля детей для определения в ДОУ'] = children_pre_school[
                            children_pre_school['Название'] == 'муниципальное образование "город Екатеринбург"']['Доля'].iloc[0]

In [101]:
accidents_people = pd.read_excel('Критерии.xlsx', sheet_name=4).rename(columns={'Unnamed: 15': 2014, 'Unnamed: 1': 'Всего'})
accidents_people.head(10)

,"Общее количество ДТП, число погибших и раненых\n (за январь - декабрь 2014 г.)",Всего,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,"Оценка численности городского и сельского населения на 1 января текущего года, человек,",...,Unnamed: 12,Unnamed: 13,Unnamed: 14,2014,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,ДТП,NaN,NaN,Погибло,NaN,Ранено,NaN,NaN,на 1 января,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,абс.,± % к \n АППГ,Уд.вес,абс.,± % к АППГ,абс.,± % к АППГ,NaN,NaN,...,2011.0,2012.0,2013,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0
2,1,2,3,4,5,6,7,8,NaN,Все население,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Российская Федерация,199720,-2.1,100,26963,-0.2,251785,-2.6,NaN,Байкаловский муниципальный район,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Белгородская область,1302,0.6,0.7,270,5.5,1462,-3.1,NaN,Муниципальный район,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Брянская область,1448,-2.6,0.7,278,6.5,1742,-6,NaN,Байкаловский муниципальный район,...,16263.0,15923.0,15730,15572.0,15351.0,15252.0,15226.0,15096.0,14952.0,14783.0
6,Владимирская область,3089,3.2,1.5,446,2.8,4184,4.1,NaN,Баженовское сельское поселение,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Воронежская область,3555,-7,1.8,633,7.3,4271,-8.6,NaN,Сельское поселение,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ивановская область,1948,0.4,1,153,стаб.,2539,-2.4,NaN,Байкаловский муниципальный район,...,3524.0,3417.0,3364,3323.0,3191.0,3130.0,3141.0,3108.0,3048.0,3020.0
9,Калужская область,2417,3.9,1.2,378,22.3,3223,1.3,NaN,Байкаловское сельское поселение,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
all_accidents = accidents_people[accidents_people.iloc[:, 0] == name]['Всего'].iloc[0]
all_people_of_name = accidents_people[2014].iloc[2:].sum()

criterions['Доля ДТП к численности населения'] = all_accidents / all_people_of_name

In [106]:
people_with_water = pd.read_excel('Критерии.xlsx', sheet_name=5).rename(columns={'Unnamed: 1': 'Доля'})
people_with_water['Доля'] /= 100
people_with_water

,"Доля населения, обеспеченного питьевой водой, отвечающей требованиям безопасности, в общей численности населения",Доля
0,2009,0.855847
1,2010,0.865299
2,2011,0.877023
3,2012,0.886224
4,2013,0.887407
5,2014,0.893831

In [107]:
criterions['Доля населения, обеспеченного безопасной питьевой водой'] = people_with_water[
                                                                            people_with_water.iloc[:, 0] == year]['Доля'].iloc[0]

In [108]:
criterions

{'Доля аварийного жилья': 0.6,
 'Доля детей для определения в ДОУ': 0.4360968153,
 'Доля ДТП к численности населения': 0.0005210013757430432,
 'Доля населения, обеспеченного безопасной питьевой водой': 0.893831}

In [111]:
name_criterions.append({'name': name,
                        'year': [{year: criterions}]})

In [98]:
import json

In [112]:
with open('criterions.json', 'w') as file:
    json.dump(name_criterions, file)

In [113]:
with open('criterions.json', 'r') as file:
    loaded_name_criterions = json.load(file)
loaded_name_criterions

[{'name': 'Свердловская область',
  'year': [{'2014': {'Доля аварийного жилья': 0.6,
     'Доля детей для определения в ДОУ': 0.4360968153,
     'Доля ДТП к численности населения': 0.0005210013757430432,
     'Доля населения, обеспеченного безопасной питьевой водой': 0.893831}}]}]